
// topicsList
export const GET_TOPICS_LIST = 'GET_TOPICS_LIST';
export const CHANGE_TOPICS_LIST_PAGE = 'CHANGE_TOPICS_LIST_PAGE';
export const CHANGE_TOPICS_LIST_TAB = 'CHANGE_TOPICS_LIST_TAB';
export const RESET_TOPICS_LIST = 'RESET_TOPICS_LIST';

// topicDetail
export const GET_TOPIC_DETAIL = 'GET_TOPIC_DETAIL';
export const RESET_TOPIC_DETAIL = 'RESET_TOPIC_DETAIL';
