'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

// topicsList
var GET_TOPICS_LIST = exports.GET_TOPICS_LIST = 'GET_TOPICS_LIST';
var CHANGE_TOPICS_LIST_PAGE = exports.CHANGE_TOPICS_LIST_PAGE = 'CHANGE_TOPICS_LIST_PAGE';
var CHANGE_TOPICS_LIST_TAB = exports.CHANGE_TOPICS_LIST_TAB = 'CHANGE_TOPICS_LIST_TAB';
var RESET_TOPICS_LIST = exports.RESET_TOPICS_LIST = 'RESET_TOPICS_LIST';

// topicDetail
var GET_TOPIC_DETAIL = exports.GET_TOPIC_DETAIL = 'GET_TOPIC_DETAIL';
var RESET_TOPIC_DETAIL = exports.RESET_TOPIC_DETAIL = 'RESET_TOPIC_DETAIL';